In [ ]:
3+7

In [ ]:
5+25

In [ ]:
print

In [ ]:
print("hello")

In [ ]:
print(7)

In [ ]:
name = "Marisol"
age = 21

In [ ]:
print(age)

In [ ]:
#This is a comment. It will not run 

In [ ]:
# ou can echo values without using print in this notebook 
name

# Variables and Values

In [ ]:
# Variables can be used in calculations 
print(age)
age = age +3 
print(age)

In [ ]:
#Order of operations matters!
first = 1
second = 2 
second = first * 5
first = 2 

print(first)
print(second)

In [ ]:
# Values have types. Types affect what you can do with them. 
print(5-3)
#print("hello" - "h")

In [ ]:
print(len("hello"))
#print(len(6))

In [ ]:
## Challenge
#Explain what each operator does 

print(5 // 3)

print(5 / 3)

print(5 % 3)

# Getting help

In [ ]:
# Rounding numbers is built in 
round(3.14159)

In [ ]:
round(3.14159, 2)

In [ ]:
help(round)

In [ ]:
round(3.14159, ndigits=2)

In [ ]:
# All functions return a new value
rounded_pi = round(3.14159, 2)
print(rounded_pi)

## Challange

In what order do the operations happen? 

radiance = 1.0 

radiance = max(2.1, 2.0 + min(radiance, 1.1 * radiance - 0.5))

In [ ]:
radiance = 1.0
radiance = max(2.1, 2.0 + min(radiance, 1.1 * radiance - 0.5))
print(radiance)

In [ ]:
# Break down these operations 
radiance = 1.0 

min_arg_2 = 1.1 * radiance - 0.5
print("Min arg 2:", min_arg_2)

min_result = min(radiance, min_arg_2)
print("Min result:", min_result)

radiance = max(2.1,2.0 + min_result)
print(radiance)

# A Brief Interlude with Git

## Libraries

In [ ]:
import math

In [ ]:
math.pi


In [ ]:
print(math.pi)
print(math.cos(math.pi))

In [ ]:
# get complete help with help ()
# help(math)

#Get a list of options with dir()
print(dir(math))

## List

In [ ]:
# A list is an ordered collection of stuff
fruits = ["apple", "banana", "cherry", "date","elderberry", "fig"]

In [ ]:
fruits

In [ ]:
len(fruits)

In [ ]:
## List are indexed by position, counting from 0 
# First item 
print(fruits[0])

# Fifth item 
print(fruits[4])

In [ ]:
# Get subsets by slicing the list 
# Get the first 3 items 
fruits[0:3]

In [ ]:
fruits[2:5]

In [ ]:
# Get items bys step 
# Get the first 5 items, every other item 
fruits[0:5:2]

In [ ]:
# Get first 5 items, every 3rd item 
fruits[0:5:3]

In [ ]:
print(len(fruits))

## Challange 
fruits[-1]

fruits[20]

fruits[-3:]

In [ ]:
print(fruits[-1])

#print(fruits[20])

print(fruits[-3:])

In [ ]:
# Why are lists indexed this way? 
print(fruits[:2])
print(fruits[2:])
print(len(fruits[1:3]))

# Adding stuff to list

In [ ]:
# Update a specific item 
print(fruits)

fruits[0] = "apricot"
print(fruits)

In [ ]:
# Add new items to the list 
fruits.append("grape")

print(fruits)

In [ ]:
# Add items from a second list to the first list
more_fruits = ["honeydew", "imbe", "jackfruit"]
fruits.extend(more_fruits)

print(fruits)

In [ ]:
# Many functions operate on collections 
# Asessing our wide receiving corp 
receiving_yards = [450, 370, 870, 150]

mean_yards = sum(receiving_yards)/len(receiving_yards)
print(mean_yards)

# For loops

In [ ]:
for fruit in fruits: 
    print(fruits)

In [ ]:
for bob in fruits: 
    print(bob)

In [ ]:
# Code blocks can contain many statements 
primes = [2, 3, 5]
for p in primes:
    squared = p ** 2
    cubed = p ** 3 
    print(p, squared, cubed)
    

In [ ]:
# Create a new collection from an existing collection 
primes_squared = []
for p in primes:
    primes_squared.append(p ** 2)

print(primes_squared)

## Challange
Get the total lenght of all the items in the fruits list.

In [ ]:
print(len(fruits))

In [ ]:
# Solution 1 
fruit_lenghts = []
for f in fruits: 
    fruit_lenghts.append(len(f))

print(fruit_lenghts)
print(sum(fruit_lenghts))

In [ ]:
# Solution 2 
count = 0 
for f in fruits: 
    count = count + len(f)
    print(count) 

print("Final count", count)

In [ ]:
# Generator comprehension 
sum(len(f) for f in fruits)

In [ ]:
print ("  ".join(fruits))

In [ ]:
print("_".join(fruits))

## Linear Algebra with NumPy

In [26]:
import numpy as np

In [28]:
# Create an array of random numbers
m_rand = np.random.rand(3,4)
print(m_rand) 

[[0.0344175  0.74771836 0.45725294 0.75190452]
 [0.68134281 0.33596099 0.07044465 0.65568941]
 [0.23546194 0.24966656 0.36446246 0.54689311]]


In [38]:
# index by row, column 
m_rand[0, 0]

0.03441749548060302

In [46]:
m_rand[0,1]

0.7477183571260192

In [36]:
# Arrays have attributes 
print(m_rand.shape)
print(m_rand.size)
print(m_rand.ndim)

(3, 4)
12
2


In [42]:
# Linear algebra
x = np.arange(9)
y = np.arange(9)

print(x)
print(y)


[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [48]:
# Operations are element-wise by default
x * y 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [50]:
# Matrix-wise operations if you like 
x @ y 

204

In [52]:
# You can reshape arrays
x1 = x.reshape(3, 3)
x2 = x.reshape(9, 1)

print(x)
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### Challange 
1. create a 3 x 3 array containing the number 0-8 
2. Multiply the array by itself (elementwise) 
3. Multiply the array by its transpose 
4. Divide the array by itself

EXAMPLE BELOW 

 1. x = np.arrange(9)
    
    x1 = np.arange(3,3)

    print(x1)

    demo = np.arange(9).reshape(3,3)

    print(demo)
    
2. demo * demo

3. demo * demo.T

4. demo / demo 


In [61]:
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [69]:
print(x1 * x1)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [67]:
np.transpose(x1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [71]:
print(x1 * np.transpose(x1))

[[ 0  3 12]
 [ 3 16 35]
 [12 35 64]]


In [77]:
result = (x1 / x1)

print(result)

[[nan  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


/var/folders/0l/x19p817n777b4f3nn_nx94xc0000gn/T/ipykernel_12939/814200593.py:1: RuntimeWarning: invalid value encountered in divide
  result = (x1 / x1)


In [83]:
print(x1) 
print(x1.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [91]:
x = np.arange(9)
x1 = x.reshape(3,3)
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [93]:
# Use methos chaining to do more work on one line 
demo = np.arange(9).reshape(3,3)
print(demo)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [95]:
demo * demo

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [97]:
# Get transpose, method 1 
demo * demo.T

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [99]:
# Get transpose, method 2 
demo * np.transpose(demo)

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [107]:
demo / demo 
# Will not work because you are dividing it by zero 

/var/folders/0l/x19p817n777b4f3nn_nx94xc0000gn/T/ipykernel_12939/761784653.py:1: RuntimeWarning: invalid value encountered in divide
  demo / demo


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# Working with data in Pandas

In [111]:
import pandas as pd

In [113]:
data = pd.read_csv("gapminder_gdp_oceania.csv")
print(data)

       country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686   
1  New Zealand     10556.57566     12247.39532     13175.67800   

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928   
1     14463.91893     16046.03728     16233.71770     17632.41040   

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473   
1     19007.19129     18363.32494     21050.41377     23189.80135   

   gdpPercap_2007  
0     34435.36744  
1     25185.00911  


In [115]:
data

country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686   
1  New Zealand     10556.57566     12247.39532     13175.67800   

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928   
1     14463.91893     16046.03728     16233.71770     17632.41040   

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473   
1     19007.19129     18363.32494     21050.41377     23189.80135   

   gdpPercap_2007  
0     34435.36744  
1     25185.00911

In [123]:
# Import csv and index by country name 
data = pd.read_csv("gapminder_gdp_oceania.csv", index_col = "country")

In [125]:
data

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                       
Australia       10039.59564     10949.64959     12217.22686     14526.12465   
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893   

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                       
Australia       16788.62948     18334.19751     19477.00928     21888.88903   
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129   

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                      
Australia       23424.76683     26997.93657     30687.75473     34435.36744  
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911

In [127]:
# Good advice about Python 
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [129]:
data

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                       
Australia       10039.59564     10949.64959     12217.22686     14526.12465   
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893   

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                       
Australia       16788.62948     18334.19751     19477.00928     21888.88903   
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129   

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                      
Australia       23424.76683     26997.93657     30687.75473     34435.36744  
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911

In [135]:
# Data frames have attributes
print(data.index)
print(data.columns)
print(data.shape)

Index(['Australia', 'New Zealand'], dtype='object', name='country')
Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')
(2, 12)


In [137]:
# data frames can tell you about their contents 
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gdpPercap_1952  2 non-null      float64
 1   gdpPercap_1957  2 non-null      float64
 2   gdpPercap_1962  2 non-null      float64
 3   gdpPercap_1967  2 non-null      float64
 4   gdpPercap_1972  2 non-null      float64
 5   gdpPercap_1977  2 non-null      float64
 6   gdpPercap_1982  2 non-null      float64
 7   gdpPercap_1987  2 non-null      float64
 8   gdpPercap_1992  2 non-null      float64
 9   gdpPercap_1997  2 non-null      float64
 10  gdpPercap_2002  2 non-null      float64
 11  gdpPercap_2007  2 non-null      float64
dtypes: float64(12)
memory usage: 208.0+ bytes


In [139]:
# Get descriptive statistics 
data.describe()

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
count        2.000000        2.000000        2.000000        2.000000   
mean     10298.085650    11598.522455    12696.452430    14495.021790   
std        365.560078      917.644806      677.727301       43.986086   
min      10039.595640    10949.649590    12217.226860    14463.918930   
25%      10168.840645    11274.086022    12456.839645    14479.470360   
50%      10298.085650    11598.522455    12696.452430    14495.021790   
75%      10427.330655    11922.958888    12936.065215    14510.573220   
max      10556.575660    12247.395320    13175.678000    14526.124650   

       gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
count         2.00000        2.000000        2.000000        2.000000   
mean      16417.33338    17283.957605    18554.709840    20448.040160   
std         525.09198     1485.263517     1304.328377     2037.668013   
min       16046.03728    16233.717700    17632.410400    19007.191290   
25%       16231.68533    16758.837652    18093.560120    19727.615725   
50%       16417.33338    17283.957605    18554.709840    20448.040160   
75%       16602.98143    17809.077558    19015.859560    21168.464595   
max       16788.62948    18334.197510    19477.009280    21888.889030   

       gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
count        2.000000        2.000000        2.000000        2.000000  
mean     20894.045885    24024.175170    26938.778040    29810.188275  
std       3578.979883     4205.533703     5301.853680     6540.991104  
min      18363.324940    21050.413770    23189.801350    25185.009110  
25%      19628.685412    22537.294470    25064.289695    27497.598692  
50%      20894.045885    24024.175170    26938.778040    29810.188275  
75%      22159.406358    25511.055870    28813.266385    32122.777858  
max      23424.766830    26997.936570    30687.754730    34435.367440

In [141]:
# Get the first N rows
data.head(1)

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                     
Australia     10039.59564     10949.64959     12217.22686     14526.12465   

           gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                     
Australia     16788.62948     18334.19751     19477.00928     21888.88903   

           gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                    
Australia     23424.76683     26997.93657     30687.75473     34435.36744

In [143]:
data.T.describe()

country     Australia   New Zealand
count       12.000000     12.000000
mean     19980.595634  17262.622813
std       7815.405220   4409.009167
min      10039.595640  10556.575660
25%      13948.900203  14141.858697
50%      18905.603395  16933.064050
75%      24318.059265  19517.996910
max      34435.367440  25185.009110

## Subsetting Data 

In [146]:
data = pd.read_csv("gapminder_gdp_europe.csv", index_col = "country")

In [148]:
data

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country                                                                  
Albania                    1601.056136     1942.284244     2312.888958   
Austria                    6137.076492     8842.598030    10750.721110   
Belgium                    8343.105127     9714.960623    10991.206760   
Bosnia and Herzegovina      973.533195     1353.989176     1709.683679   
Bulgaria                   2444.286648     3008.670727     4254.337839   
Croatia                    3119.236520     4338.231617     5477.890018   
Czech Republic             6876.140250     8256.343918    10136.867130   
Denmark                    9692.385245    11099.659350    13583.313510   
Finland                    6424.519071     7545.415386     9371.842561   
France                     7029.809327     8662.834898    10560.485530   
Germany                    7144.114393    10187.826650    12902.462910   
Greece                     3530.690067     4916.299889     6017.190733   
Hungary                    5263.673816     6040.180011     7550.359877   
Iceland                    7267.688428     9244.001412    10350.159060   
Ireland                    5210.280328     5599.077872     6631.597314   
Italy                      4931.404155     6248.656232     8243.582340   
Montenegro                 2647.585601     3682.259903     4649.593785   
Netherlands                8941.571858    11276.193440    12790.849560   
Norway                    10095.421720    11653.973040    13450.401510   
Poland                     4029.329699     4734.253019     5338.752143   
Portugal                   3068.319867     3774.571743     4727.954889   
Romania                    3144.613186     3943.370225     4734.997586   
Serbia                     3581.459448     4981.090891     6289.629157   
Slovak Republic            5074.659104     6093.262980     7481.107598   
Slovenia                   4215.041741     5862.276629     7402.303395   
Spain                      3834.034742     4564.802410     5693.843879   
Sweden                     8527.844662     9911.878226    12329.441920   
Switzerland               14734.232750    17909.489730    20431.092700   
Turkey                     1969.100980     2218.754257     2322.869908   
United Kingdom             9979.508487    11283.177950    12477.177070   

                        gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country                                                                  
Albania                    2760.196931     3313.422188     3533.003910   
Austria                   12834.602400    16661.625600    19749.422300   
Belgium                   13149.041190    16672.143560    19117.974480   
Bosnia and Herzegovina     2172.352423     2860.169750     3528.481305   
Bulgaria                   5577.002800     6597.494398     7612.240438   
Croatia                    6960.297861     9164.090127    11305.385170   
Czech Republic            11399.444890    13108.453600    14800.160620   
Denmark                   15937.211230    18866.207210    20422.901500   
Finland                   10921.636260    14358.875900    15605.422830   
France                    12999.917660    16107.191710    18292.635140   
Germany                   14745.625610    18016.180270    20512.921230   
Greece                     8513.097016    12724.829570    14195.524280   
Hungary                    9326.644670    10168.656110    11674.837370   
Iceland                   13319.895680    15798.063620    19654.962470   
Ireland                    7655.568963     9530.772896    11150.981130   
Italy                     10022.401310    12269.273780    14255.984750   
Montenegro                 5907.850937     7778.414017     9595.929905   
Netherlands               15363.251360    18794.745670    21209.059200   
Norway                    16361.876470    18965.055510    23311.349390   
Poland                     6557.152776     8006.506993     9508.141454   
Portugal                   

In [152]:
# Get item by index location
data.iloc[0,0]

1601.056136

In [154]:
# Get item by label
data.loc["Albania", "gdpPercap_1952"]

1601.056136

# A brief digression on string methods 

In [159]:
# Standard has string methods 
big_hello = "hello".title()
print(big_hello)

Hello


In [163]:
help("hello".title)

Help on built-in function title:

title() method of builtins.str instance
    Return a version of the string where each word is titlecased.

    More specifically, words start with uppercased characters and all remaining
    cased characters have lower case.



In [165]:
# What methods are available? 
print(dir("hello"))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [167]:
print(data.columns)

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')


In [169]:
print(dir(data.columns.str))

['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__frozen', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', '_doc_args', '_freeze', '_get_series_list', '_index', '_inferred_dtype', '_is_categorical', '_is_string', '_name', '_orig', '_parent', '_validate', '_wrap_result', 'capitalize', 'casefold', 'cat', 'center', 'contains', 'count', 'decode', 'encode', 'endswith', 'extract', 'extractall', 'find', 'findall', 'fullmatch', 'get', 'get_dummies', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'len', 'ljust', 'lower', 'lstrip', 'match', 'normalize', 'pad', 'partition', 'removeprefix', 'removesuffix', 'rep

In [173]:
# Rewrite column headers to strip off leading text
data.columns = data.columns.str.strip("gdpPercap_")
print(data.columns)

Index(['1952', '1957', '1962', '1967', '1972', '1977', '1982', '1987', '1992',
       '1997', '2002', '2007'],
      dtype='object')


In [175]:
data.loc["Albania", "1952"]

1601.056136

In [188]:
subset = data.loc["Italy":"Poland", "1962":"1972"]
subset

1962          1967          1972
country                                              
Italy         8243.582340  10022.401310  12269.273780
Montenegro    4649.593785   5907.850937   7778.414017
Netherlands  12790.849560  15363.251360  18794.745670
Norway       13450.401510  16361.876470  18965.055510
Poland        5338.752143   6557.152776   8006.506993

In [190]:
# Get all of the variables for a subset of rows
data.loc["Italy": "Poland", :]

1952          1957          1962          1967  \
country                                                               
Italy         4931.404155   6248.656232   8243.582340  10022.401310   
Montenegro    2647.585601   3682.259903   4649.593785   5907.850937   
Netherlands   8941.571858  11276.193440  12790.849560  15363.251360   
Norway       10095.421720  11653.973040  13450.401510  16361.876470   
Poland        4029.329699   4734.253019   5338.752143   6557.152776   

                     1972          1977          1982          1987  \
country                                                               
Italy        12269.273780  14255.984750  16537.483500  19207.234820   
Montenegro    7778.414017   9595.929905  11222.587620  11732.510170   
Netherlands  18794.745670  21209.059200  21399.460460  23651.323610   
Norway       18965.055510  23311.349390  26298.635310  31540.974800   
Poland        8006.506993   9508.141454   8451.531004   9082.351172   

                     1992          1997          2002          2007  
country                                                              
Italy        22013.644860  24675.024460  27968.098170  28569.719700  
Montenegro    7003.339037   6465.613349   6557.194282   9253.896111  
Netherlands  26790.949610  30246.130630  33724.757780  36797.933320  
Norway       33965.661150  41283.164330  44683.975250  49357.190170  
Poland        7738.881247  10159.583680  12002.239080  15389.924680

In [192]:
subset.describe()

1962          1967          1972
count      5.000000      5.000000      5.000000
mean    8894.635868  10842.506571  13162.799194
std     4093.410673   4855.106424   5517.298708
min     4649.593785   5907.850937   7778.414017
25%     5338.752143   6557.152776   8006.506993
50%     8243.582340  10022.401310  12269.273780
75%    12790.849560  15363.251360  18794.745670
max    13450.401510  16361.876470  18965.055510

In [196]:
subset.max()

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64

## Challange 

1. Calculate subset.max() and assign the results to a variable. What kind of thing is it? ~ Type
2. What is the maximum value of the new thing?
3. Can you calculate the max value of the new thing in step 1?

subset_max = subset.max()

print(subset_max)

print(type(subset))

print(type(subset_max))

In [202]:
submax = subset.max()

In [208]:
submax

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64

In [212]:
submax.max()

18965.05551

In [214]:
subset_max = subset.max()
print(subset_max)

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64


In [216]:
print(type(subset))
print(type(subset_max))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [218]:
subset_max.max()

18965.05551

In [222]:
# Solution 1 
subset.max().max()

18965.05551

In [228]:
print("Default max")
print(subset.max())
print("Max along axis 0")
print(subset.max(axis = 0))
print("Max along axis 1")
print(subset.max(axis = 1))

Default max
1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64
Max along axis 0
1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64
Max along axis 1
country
Italy          12269.273780
Montenegro      7778.414017
Netherlands    18794.745670
Norway         18965.055510
Poland          8006.506993
dtype: float64


In [231]:
# Get max for overall data frame 
subset.max(axis = None)

18965.05551

## Filter Data by Creation 

In [234]:
subset

1962          1967          1972
country                                              
Italy         8243.582340  10022.401310  12269.273780
Montenegro    4649.593785   5907.850937   7778.414017
Netherlands  12790.849560  15363.251360  18794.745670
Norway       13450.401510  16361.876470  18965.055510
Poland        5338.752143   6557.152776   8006.506993

In [238]:
# Get GDPs greater than 10,000
subset > 10000

1962   1967   1972
country                         
Italy        False   True   True
Montenegro   False  False  False
Netherlands   True   True   True
Norway        True   True   True
Poland       False  False  False

In [240]:
# filter the data frame by the criterion 
df = subset[subset > 10000]
df

1962         1967         1972
country                                           
Italy                NaN  10022.40131  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

In [242]:
# Get everything above the median 
subset[subset > subset.median(axis = None)]

1962         1967         1972
country                                           
Italy                NaN          NaN  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

In [244]:
df

1962         1967         1972
country                                           
Italy                NaN  10022.40131  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

# Working with missing data

In [259]:
# Missing data is ignored by default 
print("Columns means")
print(df.mean())

print("Rows means")
print(df.mean(axis = 1))

Columns means
1962    13120.625535
1967    13915.843047
1972    16676.358320
dtype: float64
Rows means
country
Italy          11145.837545
Montenegro              NaN
Netherlands    15649.615530
Norway         16259.111163
Poland                  NaN
dtype: float64


In [263]:
# Count our missing values 
# Missing by row 
df.isna().sum()

1962    3
1967    2
1972    2
dtype: int64

In [265]:
# Check total missing values 
df.isna().sum().sum()

7

In [267]:
# Drop missing values 
df.dropna()

1962         1967         1972
country                                           
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551

In [269]:
# Replace missing values with a fixed value 
df_fixed = df.fillna(99)
print(df_fixed)

                    1962         1967         1972
country                                           
Italy           99.00000  10022.40131  12269.27378
Montenegro      99.00000     99.00000     99.00000
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland          99.00000     99.00000     99.00000


In [271]:
# Replace misssing values with interpolated data
df_interpolated = df.interpolate()
print(df_interpolated)

                    1962          1967          1972
country                                             
Italy                NaN  10022.401310  12269.273780
Montenegro           NaN  12692.826335  15532.009725
Netherlands  12790.84956  15363.251360  18794.745670
Norway       13450.40151  16361.876470  18965.055510
Poland       13450.40151  16361.876470  18965.055510


## Challange: The perils of missing data
1. Create an array of random numbers matching the "data" data frame

random_filter = np.random.rand(30,12) * data.max(axis = None)

OR 

random_filter = np.random.rand(30,12) * 49000

2. Create a new data frame that filters out all values lower than the random numbers

3. Interpolate new values for missing data in the new data frame. How accurate are they? 

In [274]:
random_filter = np.random.rand(30,12) * data.max(axis = None)

In [276]:
print(random_filter)

[[3.03012368e+04 6.53485625e+03 2.17858014e+04 1.62935206e+04
  4.57689594e+04 4.44561400e+04 1.86665272e+04 4.26750828e+04
  2.00260450e+04 1.61496635e+04 6.53274174e+03 1.63016646e+04]
 [4.07198023e+04 1.03783548e+04 8.07989283e+03 1.86635310e+03
  3.17201525e+04 2.07423141e+04 1.28992044e+04 3.47603407e+04
  1.69567606e+04 4.81139771e+03 3.20638198e+04 4.83158199e+04]
 [2.87820401e+04 8.16698340e+03 1.87720423e+03 1.52969035e+04
  2.99664897e+04 5.31179084e+03 3.41879789e+04 3.98263449e+04
  3.17839720e+04 1.08068277e+01 5.52204245e+03 3.34691978e+04]
 [3.85822538e+04 1.58090815e+04 2.06621229e+04 3.36777404e+03
  4.20314551e+04 2.63147665e+04 2.65137045e+04 3.86420908e+04
  3.99969739e+04 3.20721354e+04 3.36594371e+02 1.41099160e+04]
 [4.68375129e+04 3.53539263e+04 2.65424624e+04 1.04137817e+04
  2.28366949e+04 2.79613969e+04 1.98554789e+04 4.23811418e+04
  1.05301598e+04 6.15337990e+02 3.73317472e+04 5.16352234e+03]
 [4.10732034e+04 3.33879581e+04 3.70312657e+04 3.24106937e+04
  2

In [291]:
new_data = data[data > random_filter]
new_data

1952          1957          1962          1967  \
country                                                                         
Albania                         NaN           NaN           NaN           NaN   
Austria                         NaN           NaN  10750.721110  12834.602400   
Belgium                         NaN   9714.960623  10991.206760           NaN   
Bosnia and Herzegovina          NaN           NaN           NaN           NaN   
Bulgaria                        NaN           NaN           NaN           NaN   
Croatia                         NaN           NaN           NaN           NaN   
Czech Republic                  NaN           NaN  10136.867130           NaN   
Denmark                         NaN           NaN           NaN  15937.211230   
Finland                         NaN           NaN           NaN           NaN   
France                          NaN           NaN           NaN           NaN   
Germany                         NaN  10187.826650           NaN           NaN   
Greece                          NaN           NaN           NaN           NaN   
Hungary                         NaN           NaN           NaN           NaN   
Iceland                         NaN           NaN           NaN           NaN   
Ireland                         NaN           NaN           NaN           NaN   
Italy                           NaN   6248.656232   8243.582340           NaN   
Montenegro                      NaN           NaN           NaN   5907.850937   
Netherlands                     NaN  11276.193440           NaN  15363.251360   
Norway                          NaN           NaN           NaN           NaN   
Poland                          NaN           NaN           NaN           NaN   
Portugal                        NaN           NaN           NaN           NaN   
Romania                         NaN           NaN           NaN           NaN   
Serbia                  3581.459448           NaN           NaN           NaN   
Slovak Republic                 NaN           NaN           NaN           NaN   
Slovenia                        NaN           NaN           NaN           NaN   
Spain                           NaN           NaN   5693.843879           NaN   
Sweden                          NaN           NaN  12329.441920           NaN   
Switzerland                     NaN           NaN           NaN  22966.144320   
Turkey                          NaN           NaN           NaN           NaN   
United Kingdom                  NaN           NaN           NaN  14142.850890   

                                1972          1977         1982          1987  \
country                                                                         
Albania                          NaN           NaN          NaN           NaN   
Austria                          NaN           NaN  21597.08362           NaN   
Belgium                          NaN  19117.974480          NaN           NaN   
Bosnia and Herzegovina           NaN           NaN          NaN           NaN   
Bulgaria                         NaN           NaN          NaN           NaN   
Croatia                          NaN           NaN          NaN           NaN   
Czech Republic                   NaN           NaN  15377.22855           NaN   
Denmark                 18866.207210  20422.901500          NaN           NaN   
Finland                 14358.875900           NaN  18533.15761           NaN   
France                           NaN           NaN  20293.89746           NaN   
Germany                          NaN  20512.921230          NaN  24639.185660   
Greece                           NaN           NaN          NaN           NaN   
Hungary                          NaN           NaN          NaN           NaN   
Iceland                 15798.063620           NaN  23269.60750  26923.206280   
Ireland                          NaN  11150.981130          NaN           NaN   
Italy                   12269.273780           NaN          N

In [293]:
new_data_imp = new_data.interpolate()

In [295]:
new_data_imp

1952          1957          1962          1967  \
country                                                                         
Albania                         NaN           NaN           NaN           NaN   
Austria                         NaN           NaN  10750.721110  12834.602400   
Belgium                         NaN   9714.960623  10991.206760  13351.703872   
Bosnia and Herzegovina          NaN   9774.068876  10777.621853  13868.805343   
Bulgaria                        NaN   9833.177130  10564.036945  14385.906815   
Croatia                         NaN   9892.285383  10350.452037  14903.008287   
Czech Republic                  NaN   9951.393637  10136.867130  15420.109758   
Denmark                         NaN  10010.501890   9926.502153  15937.211230   
Finland                         NaN  10069.610143   9716.137177  14822.837864   
France                          NaN  10128.718397   9505.772200  13708.464498   
Germany                         NaN  10187.826650   9295.407223  12594.091132   
Greece                          NaN   9399.992566   9085.042247  11479.717766   
Hungary                         NaN   8612.158483   8874.677270  10365.344401   
Iceland                         NaN   7824.324399   8664.312293   9250.971035   
Ireland                         NaN   7036.490316   8453.947317   8136.597669   
Italy                           NaN   6248.656232   8243.582340   7022.224303   
Montenegro                      NaN   8762.424836   7988.608494   5907.850937   
Netherlands                     NaN  11276.193440   7733.634648  15363.251360   
Norway                          NaN  11276.193440   7478.660802  16123.540656   
Poland                          NaN  11276.193440   7223.686956  16883.829952   
Portugal                        NaN  11276.193440   6968.713110  17644.119248   
Romania                         NaN  11276.193440   6713.739263  18404.408544   
Serbia                  3581.459448  11276.193440   6458.765417  19164.697840   
Slovak Republic         3581.459448  11276.193440   6203.791571  19924.987136   
Slovenia                3581.459448  11276.193440   5948.817725  20685.276432   
Spain                   3581.459448  11276.193440   5693.843879  21445.565728   
Sweden                  3581.459448  11276.193440  12329.441920  22205.855024   
Switzerland             3581.459448  11276.193440  12329.441920  22966.144320   
Turkey                  3581.459448  11276.193440  12329.441920  18554.497605   
United Kingdom          3581.459448  11276.193440  12329.441920  14142.850890   

                                1972          1977          1982  \
country                                                            
Albania                          NaN           NaN           NaN   
Austria                          NaN           NaN  21597.083620   
Belgium                          NaN  19117.974480  20353.112606   
Bosnia and Herzegovina           NaN  19378.959884  19109.141592   
Bulgaria                         NaN  19639.945288  17865.170578   
Croatia                          NaN  19900.930692  16621.199564   
Czech Republic                   NaN  20161.916096  15377.228550   
Denmark                 18866.207210  20422.901500  16955.193080   
Finland                 14358.875900  20452.908077  18533.157610   
France                  14646.713444  20482.914653  20293.897460   
Germany                 14934.550988  20512.921230  21037.824970   
Greece                  15222.388532  18172.436205  21781.752480   
Hungary                 15510.226076  15831.951180  22525.679990   
Iceland                 15798.063620  13491.466155  23269.607500   
Ireland                 14033.668700  11150.981130  22802.070740   
Italy                   12269.273780  14503.673820  22334.533980   
Montenegro              15532.009725  17856.366510  21866.997220   
Netherlands             18794.745670  21209.059200  21399.460460   
Norway                  18965.055510  15358.600327  26298.635310   
Poland    

In [297]:
data.describe()

1952          1957          1962          1967          1972  \
count     30.000000     30.000000     30.000000     30.000000     30.000000   
mean    5661.057435   6963.012816   8365.486814  10143.823757  12479.575246   
std     3114.060493   3677.950146   4199.193906   4724.983889   5509.691411   
min      973.533195   1353.989176   1709.683679   2172.352423   2860.169750   
25%     3241.132406   4394.874315   5373.536612   6657.939047   9057.708094   
50%     5142.469716   6066.721495   7515.733737   9366.067033  12326.379990   
75%     7236.794919   9597.220820  10931.085348  13277.182058  16523.017127   
max    14734.232750  17909.489730  20431.092700  22966.144320  27195.113040   

               1977          1982          1987          1992          1997  \
count     30.000000     30.000000     30.000000     30.000000     30.000000   
mean   14283.979110  15617.896551  17214.310727  17061.568084  19076.781802   
std     5874.464896   6453.234827   7482.957960   9109.804361  10065.457716   
min     3528.481305   3630.880722   3738.932735   2497.437901   3193.054604   
25%    10360.030300  11449.870115  12274.570680   8667.113214   9946.599306   
50%    14225.754515  15322.824720  16215.485895  17550.155945  19596.498550   
75%    19052.412163  20901.729730  23321.587723  25034.243045  27189.530312   
max    26982.290520  28397.715120  31540.974800  33965.661150  41283.164330   

               2002          2007  
count     30.000000     30.000000  
mean   21711.732422  25054.481636  
std    11197.355517  11800.339811  
min     4604.211737   5937.029526  
25%    11721.851483  14811.898210  
50%    23674.863230  28054.065790  
75%    30373.363307  33817.962533  
max    44683.975250  49357.190170

In [299]:
new_data_imp.describe()

1952          1957          1962          1967          1972  \
count  8.000000e+00     28.000000     29.000000     29.000000     23.000000   
mean   3.581459e+03  10144.182296   9071.252262  15086.154208  14239.663033   
std    4.861454e-13   1390.813201   2023.368590   4413.804839   2659.802178   
min    3.581459e+03   6248.656232   5693.843879   5907.850937   9022.247417   
25%    3.581459e+03   9759.291813   7478.660802  12834.602400  12554.890874   
50%    3.581459e+03  10158.272523   9085.042247  14903.008287  14367.812189   
75%    3.581459e+03  11276.193440  10564.036945  18404.408544  15521.117901   
max    3.581459e+03  11276.193440  12329.441920  22966.144320  18965.055510   

               1977          1982          1987          1992          1997  \
count     28.000000     29.000000     20.000000     29.000000     29.000000   
mean   18267.397081  19049.414028  22893.955678  23123.867544  22574.106541   
std     4049.667597   3204.793203   6212.713203   5190.596949   9287.438444   
min     9508.141454  11753.842910   5089.043686  14297.021220   5970.388760   
25%    15713.613467  17865.170578  21195.691398  18603.064520  13915.041063   
50%    19248.467182  18533.157610  24554.239969  23377.735932  25266.594990   
75%    20460.409721  21597.083620  26224.894897  26108.306874  28061.099660   
max    26982.290520  26298.635310  31540.974800  33965.661150  41283.164330   

               2002          2007  
count     29.000000     28.000000  
mean   27835.233605  32317.118577  
std    10656.296735   9143.396290  
min     6018.975239  10680.792820  
25%    22514.254800  28368.580402  
50%    30035.801980  33449.844740  
75%    34480.957710  37739.350818  
max    44683.975250  49357.190170

## Sorting and Grouping 

In [310]:
# Z score all of the GDP data points
z = (data - data.mean(axis = None))/data.values.std(ddof=1)
z

1952      1957      1962      1967      1972  \
country                                                                    
Albania                -1.375535 -1.339060 -1.299445 -1.251631 -1.192496   
Austria                -0.890669 -0.601470 -0.397506 -0.174755  0.234324   
Belgium                -0.654862 -0.508221 -0.371800 -0.141144  0.235448   
Bosnia and Herzegovina -1.442612 -1.401944 -1.363923 -1.314467 -1.240945   
Bulgaria               -1.285400 -1.225071 -1.091919 -0.950537 -0.841454   
Croatia                -1.213253 -1.082952 -0.961131 -0.802673 -0.567105   
Czech Republic         -0.811669 -0.664136 -0.463122 -0.328163 -0.145483   
Denmark                -0.510634 -0.360207 -0.094724  0.156890  0.469977   
Finland                -0.859944 -0.740129 -0.544898 -0.379237 -0.011822   
France                 -0.795243 -0.620685 -0.417841 -0.157084  0.175059   
Germany                -0.783024 -0.457675 -0.167502  0.029518  0.379115   
Greece                 -1.169272 -1.021161 -0.903484 -0.636691 -0.186489   
Hungary                -0.984029 -0.901027 -0.739600 -0.549729 -0.459724   
Iceland                -0.769815 -0.558563 -0.440323 -0.122881  0.142016   
Ireland                -0.989736 -0.948177 -0.837809 -0.728354 -0.527909   
Italy                  -1.019546 -0.878742 -0.665500 -0.475358 -0.235185   
Montenegro             -1.263669 -1.153070 -1.049669 -0.915171 -0.715223   
Netherlands            -0.590890 -0.341337 -0.179432  0.095538  0.462338   
Norway                 -0.467553 -0.300955 -0.108931  0.202283  0.480543   
Poland                 -1.115971 -1.040620 -0.976004 -0.845766 -0.690841   
Portugal               -1.218695 -1.143203 -1.041293 -0.866678 -0.582267   
Romania                -1.210540 -1.125159 -1.040540 -0.854989 -0.690317   
Serbia                 -1.163845 -1.014235 -0.874362 -0.692423 -0.421947   
Slovak Republic        -1.004233 -0.895352 -0.747003 -0.647401 -0.512581   
Slovenia               -1.096120 -0.920043 -0.755426 -0.541301 -0.222976   
Spain                  -1.136846 -1.058733 -0.938047 -0.692230 -0.409475   
Sweden                 -0.635114 -0.487172 -0.228753  0.084319  0.359431   
Switzerland             0.028300  0.367711  0.637251  0.908228  1.360272   
Turkey                 -1.336193 -1.309507 -1.298378 -1.244559 -1.177822   
United Kingdom         -0.479943 -0.340591 -0.212961 -0.034914  0.152390   

                            1977      1982      1987      1992      1997  \
country                                                                    
Albania                -1.169024 -1.158562 -1.147012 -1.279718 -1.205362   
Austria                 0.564385  0.761886  0.985370  1.343908  1.563454   
Belgium                 0.496889  0.695908  0.861133  1.187156  1.399404   
Bosnia and Herzegovina -1.169508 -1.105572 -1.085530 -1.274444 -1.037188   
Bulgaria               -0.732985 -0.667573 -0.665898 -0.872973 -0.908487   
Croatia                -0.338217 -0.133365 -0.069148 -0.643671 -0.491049   
Czech Republic          0.035348  0.097032  0.196785 -0.018434  0.168787   
Denmark                 0.636375  0.771609  1.138050  1.276001  1.639179   
Finland                 0.121424  0.434376  0.713136  0.660347  0.989232   
France                  0.408666  0.622586  0.812057  1.093970  1.220743   
Germany                 0.645998  0.808325  1.087063  1.286537  1.423742   
Greece                 -0.029283  0.085401  0.176485  0.328375  0.457309   
Hungary                -0.298725 -0.205606 -0.158521 -0.420498 -0.294670   
Iceland                 0.554288  0.940666  1.331208  1.141066  1.452840   
Ireland                -0.354721 -0.197874 -0.063773  0.330227  1.074532   
Italy                  -0.022821  0.221054  0.506430  0.806413  1.090894   
Montenegro             -0.520944 -0.347067 -0.292560 -0.798072 -0.855551   
Netherlands             0.720409  0.740762  0.981469  1.317070  1.686402   
Norway                  0.945128  1.264446  1.824811  2.083992  2.866176   

In [308]:
data.mean(axis = None)

14469.475533302222

In [312]:
z

1952      1957      1962      1967      1972  \
country                                                                    
Albania                -1.375535 -1.339060 -1.299445 -1.251631 -1.192496   
Austria                -0.890669 -0.601470 -0.397506 -0.174755  0.234324   
Belgium                -0.654862 -0.508221 -0.371800 -0.141144  0.235448   
Bosnia and Herzegovina -1.442612 -1.401944 -1.363923 -1.314467 -1.240945   
Bulgaria               -1.285400 -1.225071 -1.091919 -0.950537 -0.841454   
Croatia                -1.213253 -1.082952 -0.961131 -0.802673 -0.567105   
Czech Republic         -0.811669 -0.664136 -0.463122 -0.328163 -0.145483   
Denmark                -0.510634 -0.360207 -0.094724  0.156890  0.469977   
Finland                -0.859944 -0.740129 -0.544898 -0.379237 -0.011822   
France                 -0.795243 -0.620685 -0.417841 -0.157084  0.175059   
Germany                -0.783024 -0.457675 -0.167502  0.029518  0.379115   
Greece                 -1.169272 -1.021161 -0.903484 -0.636691 -0.186489   
Hungary                -0.984029 -0.901027 -0.739600 -0.549729 -0.459724   
Iceland                -0.769815 -0.558563 -0.440323 -0.122881  0.142016   
Ireland                -0.989736 -0.948177 -0.837809 -0.728354 -0.527909   
Italy                  -1.019546 -0.878742 -0.665500 -0.475358 -0.235185   
Montenegro             -1.263669 -1.153070 -1.049669 -0.915171 -0.715223   
Netherlands            -0.590890 -0.341337 -0.179432  0.095538  0.462338   
Norway                 -0.467553 -0.300955 -0.108931  0.202283  0.480543   
Poland                 -1.115971 -1.040620 -0.976004 -0.845766 -0.690841   
Portugal               -1.218695 -1.143203 -1.041293 -0.866678 -0.582267   
Romania                -1.210540 -1.125159 -1.040540 -0.854989 -0.690317   
Serbia                 -1.163845 -1.014235 -0.874362 -0.692423 -0.421947   
Slovak Republic        -1.004233 -0.895352 -0.747003 -0.647401 -0.512581   
Slovenia               -1.096120 -0.920043 -0.755426 -0.541301 -0.222976   
Spain                  -1.136846 -1.058733 -0.938047 -0.692230 -0.409475   
Sweden                 -0.635114 -0.487172 -0.228753  0.084319  0.359431   
Switzerland             0.028300  0.367711  0.637251  0.908228  1.360272   
Turkey                 -1.336193 -1.309507 -1.298378 -1.244559 -1.177822   
United Kingdom         -0.479943 -0.340591 -0.212961 -0.034914  0.152390   

                            1977      1982      1987      1992      1997  \
country                                                                    
Albania                -1.169024 -1.158562 -1.147012 -1.279718 -1.205362   
Austria                 0.564385  0.761886  0.985370  1.343908  1.563454   
Belgium                 0.496889  0.695908  0.861133  1.187156  1.399404   
Bosnia and Herzegovina -1.169508 -1.105572 -1.085530 -1.274444 -1.037188   
Bulgaria               -0.732985 -0.667573 -0.665898 -0.872973 -0.908487   
Croatia                -0.338217 -0.133365 -0.069148 -0.643671 -0.491049   
Czech Republic          0.035348  0.097032  0.196785 -0.018434  0.168787   
Denmark                 0.636375  0.771609  1.138050  1.276001  1.639179   
Finland                 0.121424  0.434376  0.713136  0.660347  0.989232   
France                  0.408666  0.622586  0.812057  1.093970  1.220743   
Germany                 0.645998  0.808325  1.087063  1.286537  1.423742   
Greece                 -0.029283  0.085401  0.176485  0.328375  0.457309   
Hungary                -0.298725 -0.205606 -0.158521 -0.420498 -0.294670   
Iceland                 0.554288  0.940666  1.331208  1.141066  1.452840   
Ireland                -0.354721 -0.197874 -0.063773  0.330227  1.074532   
Italy                  -0.022821  0.221054  0.506430  0.806413  1.090894   
Montenegro             -0.520944 -0.347067 -0.292560 -0.798072 -0.855551   
Netherlands             0.720409  0.740762  0.981469  1.317070  1.686402   
Norway                  0.945128  1.264446  1.824811  2.083992  2.866176   

In [314]:
# Get mean z score for each country 
mean_z = z.mean(axis=1)
mean_z

country
Albania                  -1.198702
Austria                   0.635201
Belgium                   0.580562
Bosnia and Herzegovina   -1.174179
Bulgaria                 -0.864269
Croatia                  -0.549187
Czech Republic           -0.058733
Denmark                   0.769875
Finland                   0.321131
France                    0.466488
Germany                   0.650676
Greece                   -0.053493
Hungary                  -0.382813
Iceland                   0.647975
Ireland                   0.137798
Italy                     0.189812
Montenegro               -0.776189
Netherlands               0.778109
Norway                    1.312405
Poland                   -0.647011
Portugal                 -0.333010
Romania                  -0.766343
Serbia                   -0.552037
Slovak Republic          -0.433335
Slovenia                 -0.042211
Spain                    -0.046995
Sweden                    0.585091
Switzerland               1.347362
Turkey      

In [316]:
bool_z = mean_z >0
bool_z

country
Albania                   False
Austria                    True
Belgium                    True
Bosnia and Herzegovina    False
Bulgaria                  False
Croatia                   False
Czech Republic            False
Denmark                    True
Finland                    True
France                     True
Germany                    True
Greece                    False
Hungary                   False
Iceland                    True
Ireland                    True
Italy                      True
Montenegro                False
Netherlands                True
Norway                     True
Poland                    False
Portugal                  False
Romania                   False
Serbia                    False
Slovak Republic           False
Slovenia                  False
Spain                     False
Sweden                     True
Switzerland                True
Turkey                    False
United Kingdom             True
dtype: bool

In [318]:
# Add new column to data frame 
data["mean_z"] = mean_z
data["wealthy"] = bool_z

In [320]:
data.head(3)

1952         1957          1962          1967          1972  \
country                                                                       
Albania  1601.056136  1942.284244   2312.888958   2760.196931   3313.422188   
Austria  6137.076492  8842.598030  10750.721110  12834.602400  16661.625600   
Belgium  8343.105127  9714.960623  10991.206760  13149.041190  16672.143560   

                1977          1982          1987          1992          1997  \
country                                                                        
Albania   3533.00391   3630.880722   3738.932735   2497.437901   3193.054604   
Austria  19749.42230  21597.083620  23687.826070  27042.018680  29095.920660   
Belgium  19117.97448  20979.845890  22525.563080  25575.570690  27561.196630   

                 2002          2007    mean_z  wealthy  
country                                                 
Albania   4604.211737   5937.029526 -1.198702    False  
Austria  32417.607690  36126.492700  0.635201     True  
Belgium  30485.883750  33692.605080  0.580562     True

In [322]:
# Get descriptive statistics for groups 
data.groupby("wealthy").mean()

1952         1957          1962          1967          1972  \
wealthy                                                                       
False    3460.797562  4356.915102   5381.266911   6789.774524   8589.054224   
True     8175.640146  9941.410203  11776.023847  13977.022880  16925.884987   

                 1977          1982          1987          1992          1997  \
wealthy                                                                         
False    10123.062167  10999.519354  11657.755578   9814.771634  11010.972268   
True     19039.312758  20896.041919  23564.659468  25343.621170  28294.849840   

                 2002          2007    mean_z  
wealthy                                        
False    12762.305369  15908.649976 -0.559215  
True     31939.649055  35506.860676  0.639102

In [324]:
data.groupby("wealthy").describe()

1952                                                      \
        count         mean          std          min          25%   
wealthy                                                             
False    16.0  3460.797562  1472.093863   973.533195  2596.760863   
True     14.0  8175.640146  2522.755539  4931.404155  6575.841635   

                                                1957               ...  \
                 50%          75%          max count         mean  ...   
wealthy                                                            ...   
False    3337.651627  4075.757709   6876.14025  16.0  4356.915102  ...   
True     7805.396778  9504.681898  14734.23275  14.0  9941.410203  ...   

                 2007              mean_z                                \
                  75%          max  count      mean       std       min   
wealthy                                                                   
False    21090.562955  28821.06370   16.0 -0.559215  0.397648 -1.198702   
True     36643.647287  49357.19017   14.0  0.639102  0.350282  0.137798   

                                                 
              25%       50%       75%       max  
wealthy                                          
False   -0.798209 -0.550612 -0.264441 -0.042211  
True     0.481103  0.610146  0.740075  1.347362  

[2 rows x 104 columns]

# Write output 
data.to_csv()

In [329]:
# Write out output 
data.to_csv("europe_normed.csv")

## Looping over data sets 

In [332]:
import pandas as pd

In [405]:
# Import the data from files in a list 
file_list = ["gapminder_gdp_africa.csv", "gapminder_gdp_asia.csv"]

for filename in file_list:
    data = pd.read_csv(filename, index_col = "country")
    print(filename)
    print(data.head(1))

gapminder_gdp_africa.csv
         gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                   
Algeria     2449.008185     3013.976023      2550.81688     3246.991771   

         gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                   
Algeria     4182.663766     4910.416756     5745.160213     5681.358539   

         gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                  
Algeria     5023.216647     4797.295051     5288.040382     6223.367465  
gapminder_gdp_asia.csv
             gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                       
Afghanistan      779.445314       820.85303       853.10071      836.197138   

             gdpPercap_1972  gdpPercap_1

In [336]:
# Automatically get a list of files
import glob

In [340]:
glob.glob("*.csv")

['gapminder_gdp_americas.csv',
 'species.csv',
 'gapminder_gdp_europe.csv',
 'gapminder_all.csv',
 'gapminder_gdp_oceania.csv',
 'gapminder_gdp_africa.csv',
 'surveys.csv',
 'iris.csv',
 'europe_normed.csv',
 'anscombe.csv',
 'plots.csv',
 'gapminder_gdp_asia.csv']

In [344]:
# Get all the csv or tsv files 
glob.glob("*.?sv")

['gapminder_gdp_americas.csv',
 'species.csv',
 'gapminder_gdp_europe.csv',
 'gapminder_all.csv',
 'gapminder_gdp_oceania.csv',
 'gapminder_gdp_africa.csv',
 'surveys.csv',
 'iris.csv',
 'europe_normed.csv',
 'anscombe.csv',
 'plots.csv',
 'gapminder_gdp_asia.csv']

In [346]:
# Get a list of all the countries 
glob.glob("gapminder_gdp_*.csv")

['gapminder_gdp_americas.csv',
 'gapminder_gdp_europe.csv',
 'gapminder_gdp_oceania.csv',
 'gapminder_gdp_africa.csv',
 'gapminder_gdp_asia.csv']

In [353]:
# Get continent-level data and aggregatezz into 1 data frame 
data_frames = []

for filename in glob.glob("gapminder_gdp_*.csv"):
    print(filename)
    data = pd.read_csv(filename, index_col = "country")
    data_frames.append(data)

# Concatenate data frames 
all_data = pd.concat(data_frames)

gapminder_gdp_americas.csv
gapminder_gdp_europe.csv
gapminder_gdp_oceania.csv
gapminder_gdp_africa.csv
gapminder_gdp_asia.csv


In [355]:
# Inspect our results 
print(all_data.shape)
print(all_data.index)


(142, 13)
Index(['Argentina', 'Bolivia', 'Brazil', 'Canada', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Dominican Republic', 'Ecuador',
       ...
       'Philippines', 'Saudi Arabia', 'Singapore', 'Sri Lanka', 'Syria',
       'Taiwan', 'Thailand', 'Vietnam', 'West Bank and Gaza', 'Yemen Rep.'],
      dtype='object', name='country', length=142)


In [359]:
print(all_data.shape)

(142, 13)


## Conditionals 

In [362]:
# Does a file and in "all.csv"?
for filename in glob.glob("gapminder*.csv"):
    print("Current file:", filename)
    print(filename.endswith("all.csv"))

Current file: gapminder_gdp_americas.csv
False
Current file: gapminder_gdp_europe.csv
False
Current file: gapminder_all.csv
True
Current file: gapminder_gdp_oceania.csv
False
Current file: gapminder_gdp_africa.csv
False
Current file: gapminder_gdp_asia.csv
False


In [364]:
# Get truth value of a statement 
mass = 3 

print(mass == 3)
print(mass > 5)
print(mass < 4)

True
False
True


In [366]:
# Test for membership in a collection 
primes = [2,3,5]

print(2 in primes)
print(7 in primes)

True
False


In [368]:
# Testing for missing values 
df

array([3.03012368e+04, 6.53485625e+03, 2.17858014e+04, 1.62935206e+04,
       4.57689594e+04, 4.44561400e+04, 1.86665272e+04, 4.26750828e+04,
       2.00260450e+04, 1.61496635e+04, 6.53274174e+03, 1.63016646e+04,
       4.07198023e+04, 1.03783548e+04, 8.07989283e+03, 1.86635310e+03,
       3.17201525e+04, 2.07423141e+04, 1.28992044e+04, 3.47603407e+04,
       1.69567606e+04, 4.81139771e+03, 3.20638198e+04, 4.83158199e+04,
       2.87820401e+04, 8.16698340e+03, 1.87720423e+03, 1.52969035e+04,
       2.99664897e+04, 5.31179084e+03, 3.41879789e+04, 3.98263449e+04,
       3.17839720e+04, 1.08068277e+01, 5.52204245e+03, 3.34691978e+04,
       3.85822538e+04, 1.58090815e+04, 2.06621229e+04, 3.36777404e+03,
       4.20314551e+04, 2.63147665e+04, 2.65137045e+04, 3.86420908e+04,
       3.99969739e+04, 3.20721354e+04, 3.36594371e+02, 1.41099160e+04,
       4.68375129e+04, 3.53539263e+04, 2.65424624e+04, 1.04137817e+04,
       2.28366949e+04, 2.79613969e+04, 1.98554789e+04, 4.23811418e+04,
      

In [370]:
df = subset[subset > 10000]

In [372]:
df

1962         1967         1972
country                                           
Italy                NaN  10022.40131  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

In [380]:
# Are you missing any data
df.isna().any().any()

True

In [384]:
# Make choices with if - then statement 
mass = 3.5 

if mass > 3.0:
    print(mass, "is large")

3.5 is large


In [390]:
# Test for files ending in "all.csv"
data_frames = []

for filename in glob.glob("gapminder*.csv"):
    print(filename)
    if not filename.endswith("all.csv"):
        print("Passes test:", filename)
        data = pd.read_csv(filename, index_col = "country")
        data_frames.append(data)
all_data = pd.concat(data_frames)
print(all_data.shape)

gapminder_gdp_americas.csv
Passes test: gapminder_gdp_americas.csv
gapminder_gdp_europe.csv
Passes test: gapminder_gdp_europe.csv
gapminder_all.csv
gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_oceania.csv
gapminder_gdp_africa.csv
Passes test: gapminder_gdp_africa.csv
gapminder_gdp_asia.csv
Passes test: gapminder_gdp_asia.csv
(142, 13)


In [394]:
# Add an else condition 
mass = 3.5 

if mass > 3.0:
    print(mass, "is large")
else:
    print(mass, "is small")

3.5 is large


In [398]:
data_frames = []

for filename in glob.glob("gapminder*.csv"):
    if filename.endswith("all.csv"):
        print("I don't want any of that")
    else:
        print("Passes test:", filename)
        data = pd.read_csv(filename, index_col = "country")
        data_frames.append(data)

all_data = pd.concat(data_frames)
print(all_data.shape)

Passes test: gapminder_gdp_americas.csv
Passes test: gapminder_gdp_europe.csv
I don't want any of that
Passes test: gapminder_gdp_oceania.csv
Passes test: gapminder_gdp_africa.csv
Passes test: gapminder_gdp_asia.csv
(142, 13)


## Challenge 1 
1. Iterate through all the CSV files in the directory
2. Print the name and length (number of rows) of any file less than 30 rows long 

In [419]:
data_frames = []

for filename in glob.glob("*.csv"):
    data = pd.read_csv(filename)
    if data.shape[0] < 30:
        print(filename, data.shape[0])
    

gapminder_gdp_americas.csv 25
gapminder_gdp_oceania.csv 2
anscombe.csv 11
plots.csv 24


## Challenge 2 
1. Iterate through all the CSV files in the diretory
2. Print any file name that includes "europe", then print the column names for that file 

In [427]:
##MINE

data_frames = []

for filename in glob.glob("*europe*.csv"):
    if filename.endswith("all.csv"):
        print("Not that one")
    else: 
        print(filename)
        data = pd.read_csv(filename, index_col = "country")
        data_frames.append(data)
        print(data.columns)

gapminder_gdp_europe.csv
Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')
europe_normed.csv
Index(['1952', '1957', '1962', '1967', '1972', '1977', '1982', '1987', '1992',
       '1997', '2002', '2007', 'mean_z', 'wealthy'],
      dtype='object')


In [433]:
# challenge number two
data_frames = []

for filename in glob.glob("*.csv"):
    # A string is kind of like a list
    if "europe" in filename: 
        print(filename)
        data = pd.read_csv(filename)
        print(data.columns)
    

gapminder_gdp_europe.csv
Index(['country', 'gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962',
       'gdpPercap_1967', 'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982',
       'gdpPercap_1987', 'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002',
       'gdpPercap_2007'],
      dtype='object')
europe_normed.csv
Index(['country', '1952', '1957', '1962', '1967', '1972', '1977', '1982',
       '1987', '1992', '1997', '2002', '2007', 'mean_z', 'wealthy'],
      dtype='object')


In [441]:
# You can specify additional test with elif 

mass = 2

if mass > 9.0: 
    print(mass, "is huge")
elif mass > 3.0:
    print(mass, "is large")
else: 
    print(mass, "is small")


2 is small


In [449]:
# You can do more complicated tests
mass = [1, 2, 3, 4, 5,]
velocity = [5, 4, 3, 2, 5]

# Get each pair of measurements 
for m, v  in zip(mass, velocity):
    if m <= 3 and v <= 3:
        print("Small and slow")
    elif m <= 3 and v > 3:
        print("Small and fast")
    elif m > 3 and v <= 3:
        print("Large and slow")
    else: 
        print("Check data")

Small and fast
Small and fast
Small and slow
Large and slow
Check data


# Functions

In [456]:
def print_greeting():
    print("Hello!")

In [458]:
print_greeting()

Hello!


In [464]:
# Functions take arguments 
def print_date(year, month, day):
    joined_date = "/".join([year, month, day])
    print(joined_date)

In [466]:
print_date("1872", "3", "9")

1872/3/9


In [468]:
# Functions take arguments 
def print_date(year, month, day):
    joined_date = "/".join([str(year), str(month), str(day)])
    print(joined_date)

In [470]:
print_date("1872", "3", "9")
print_date(1872,3,9)

1872/3/9
1872/3/9


In [484]:
# Test your data inside your function 
def average(values):
    """Return average of values, or None if no values are supplied."""

    if len(values) == 0:
        return None 
    else:
        return sum(values) / len(values)

In [488]:
a1 = average([1, 2, 3])
print(a1)

2.0


In [490]:
a2 = average([])
print(a2)

None


In [494]:
#a3 = average(3)
#print(a3)

## Challenge

Write a function that encapsulates the z-score calculation. Your function should do the following: 

1. Read a csv file into a dataframe
2. Calculate the z-score for each item
3. Calculate the mean z-score for each country
4. Append the mean z-score as a new column
5. Return the data frame

EXTRA CREDIT: Stick all of this through a pipeline for ALL files!!!!

In [499]:
import scipy.stats as stats

In [501]:
stats

<module 'scipy.stats' from '/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/__init__.py'>

In [517]:
print(pd.__version__)

2.2.2


In [519]:
#overall_mean = data.values.mean()
#overall_std = data.values.std

In [521]:
pd.__version__

'2.2.2'

In [523]:
def norm_data(filename, index_col = None):
    """ Add a Z score to a data frame."""
  
    #Import the data 
    df = pd.read_csv(filename, index_col = index_col)

    # Calculate individual Z scores 
    z = (data - data.values.mean())/ data.values.std()

    #Mean Z score for each country 
    mean_z = z.mean(axis=1)

    #Add new column to data frame 
    data["mean_z"] = mean_z
    
    return data

In [525]:
df = norm_data("gapminder_gdp_europe.csv", index_col = "country")

In [527]:
df

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country                                                              
Afghanistan             779.445314      820.853030      853.100710   
Bahrain                9867.084765    11635.799450    12753.275140   
Bangladesh              684.244172      661.637458      686.341554   
Cambodia                368.469286      434.038336      496.913648   
China                   400.448611      575.987001      487.674018   
Hong Kong China        3054.421209     3629.076457     4692.648272   
India                   546.565749      590.061996      658.347151   
Indonesia               749.681655      858.900271      849.289770   
Iran                   3035.326002     3290.257643     4187.329802   
Iraq                   4129.766056     6229.333562     8341.737815   
Israel                 4086.522128     5385.278451     7105.630706   
Japan                  3216.956347     4317.694365     6576.649461   
Jordan                 1546.907807     1886.080591     2348.009158   
Korea Dem. Rep.        1088.277758     1571.134655     1621.693598   
Korea Rep.             1030.592226     1487.593537     1536.344387   
Kuwait               108382.352900   113523.132900    95458.111760   
Lebanon                4834.804067     6089.786934     5714.560611   
Malaysia               1831.132894     1810.066992     2036.884944   
Mongolia                786.566857      912.662609     1056.353958   
Myanmar                 331.000000      350.000000      388.000000   
Nepal                   545.865723      597.936356      652.396859   
Oman                   1828.230307     2242.746551     2924.638113   
Pakistan                684.597144      747.083529      803.342742   
Philippines            1272.880995     1547.944844     1649.552153   
Saudi Arabia           6459.554823     8157.591248    11626.419750   
Singapore              2315.138227     2843.104409     3674.735572   
Sri Lanka              1083.532030     1072.546602     1074.471960   
Syria                  1643.485354     2117.234893     2193.037133   
Taiwan                 1206.947913     1507.861290     1822.879028   
Thailand                757.797418      793.577415     1002.199172   
Vietnam                 605.066492      676.285448      772.049160   
West Bank and Gaza     1515.592329     1827.067742     2198.956312   
Yemen Rep.              781.717576      804.830455      825.623201   

                    gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country                                                              
Afghanistan             836.197138      739.981106      786.113360   
Bahrain               14804.672700    18268.658390    19340.101960   
Bangladesh              721.186086      630.233627      659.877232   
Cambodia                523.432314      421.624026      524.972183   
China                   612.705693      676.900092      741.237470   
Hong Kong China        6197.962814     8315.928145    11186.141250   
India                   700.770611      724.032527      813.337323   
Indonesia               762.431772     1111.107907     1382.702056   
Iran                   5906.731805     9613.818607    11888.595080   
Iraq                   8931.459811     9576.037596    14688.235070   
Israel                 8393.741404    12786.932230    13306.619210   
Japan                  9847.788607    14778.786360    16610.377010   
Jordan                 2741.796252     2110.856309     2852.351568   
Korea Dem. Rep.        2143.540609     3701.621503     4106.301249   
Korea Rep.             2029.228142     3030.876650     4657.221020   
Kuwait                80894.883260   109347.867000    59265.477140   
Lebanon                6006.983042     7486.384341     8659.696836   
Malaysia               2277.742396     2849.094780     3827.921571   
Mongolia               1226.041130     1421.741975     1647.511665   
Myanmar                 349.000000      357.000000      371.000000   
Nepal                   676.4

In [537]:
def norm_data(filename, index_col = None):
    """ Add a Z score to a data frame."""
  
    #Import the data 
    df = pd.read_csv(filename, index_col = index_col)

    # Drop the continent column if necessary. This returns a new data frame. 
    if "continent" in data.columns:
        data.drop("continent", axis = 1)

    # Calculate individual Z scores 
    z = (data - data.values.mean())/ data.values.std()

    #Mean Z score for each country 
    mean_z = z.mean(axis=1)

    #Add new column to data frame 
    data["mean_z"] = mean_z
    
    return data

In [539]:
df = norm_data("gapminder_gdp_europe.csv", index_col= "country")

In [541]:
print(df.columns)

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007',
       'mean_z'],
      dtype='object')


# Putting it all together 

In [544]:
# Get all the files we care about and get Z scores by continent
data_frames = []

for filename in glob.glob("gapminder*.csv"):
    if not filename.endswith("all.csv"):
        df = norm_data(filename, index_col = "country")
        data_frames.append(df)
        
all_data = pd.concat(data_frames)

print(all_data.shape)
print(all_data.columns)

(165, 13)
Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007',
       'mean_z'],
      dtype='object')
